[package]
name = "fastrock-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
fastrock-cache = { path = "../fastrock-cache" }
keyring.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
