//! Code generated by `slint-build` from `ui/app.slint`.

#![allow(
    clippy::all,
    clippy::pedantic,
    clippy::restriction,
    clippy::nursery,
    unused_qualifications,
    unreachable_pub
)]

slint::include_modules!();
